### ISSUE TITLE
Regarding digitaloceam/openvswitch_exporter support for netdev datapath

### ISSUE THREAD

**Issue by gbharanikumar** [digitalocean/openvswitch_exporter#8]
Hi,

Do we have openvswitch_exporter support for netdev datapath?
Incase we dont have openvswitch_exporter support for netdev datapath, is there a way to abstract away the datapath behind an interface, so that netdev can also be used with the openvswitch_exporter?

Regards,
Bharani..

**Comment by nicboul** [comment]
please reopen the issue if you still have it
